include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
 plugins:
  - custom_lint

# custom_lint:
#   enable_all_lint_rules: false
#   rules:
#     - sugi_lint
#   errors:
#     - sugi_lint: warning