include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
 plugins:
  - custom_lint

custom_lint:
  debugger: false
  enable_all_lint_rules: false
  rules:
    - clean_architecture_lint
  errors:
    - clean_architecture_lint: warning