name: clean_architecture_lint
description: Custom lints rules used in Clean Architecture.
homepage: https://github.com/ho-doan/clean_architecture
repository: https://github.com/ho-doan/clean_architecture
version: 0.0.1
environment:
  sdk: '>=3.0.0 <4.0.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  analyzer: ^5.12.0
  analyzer_plugin: ^0.11.2
  custom_lint_builder: ^0.5.0
dev_dependencies:
  custom_lint:
  lints: ^2.0.0